// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBr_-ZWafvZ_RZAI76a3XNs39eEH-Cws',
    appId: '1:187691664429:web:4867649d488ea2e0ffa4a4',
    messagingSenderId: '187691664429',
    projectId: 'appdid-fc290',
    authDomain: 'appdid-fc290.firebaseapp.com',
    storageBucket: 'appdid-fc290.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUIsyDznwDovYlKtjGbMaEBc22C0xlEnA',
    appId: '1:187691664429:android:0c3b7bf27076a28effa4a4',
    messagingSenderId: '187691664429',
    projectId: 'appdid-fc290',
    storageBucket: 'appdid-fc290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5rvJPRyrYATS2_XsgabSpDyfa7vUqXWs',
    appId: '1:187691664429:ios:d3f5a268d8b5c1fdffa4a4',
    messagingSenderId: '187691664429',
    projectId: 'appdid-fc290',
    storageBucket: 'appdid-fc290.appspot.com',
    androidClientId: '187691664429-7n030gn8l2gi6lhufdor3p1cqe01505o.apps.googleusercontent.com',
    iosClientId: '187691664429-9o7ndc33l5q1boomls5u6t3sh008ugc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakestoreAppGetx',
  );
}
